server {
    listen 80 default_server;
    server_name _;
    # HTTP → HTTPS редирект
    return 301 https://$host:1443$request_uri;
}

server {
    listen 1443 ssl;
    listen [::]:1443 ssl;

    ssl_certificate     /root/cert/vkosarev.link.fullchain.pem;
    ssl_certificate_key /root/cert/vkosarev.link_privatekey.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /etc/nginx/www/vkosarev.link;
    index index.html index.htm index.nginx-debian.html;
    server_name vkosarev.link;

    location / {
        try_files $uri $uri/ =404;
    }

    # Автоиндекс папки /a/ — для раздачи файлов
    location /a/ {
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;
    }

    error_page 502 /502_custom_embedded.html;
    location = /502_custom_embedded.html {
        internal;
        root /etc/nginx/www;
    }
}

server {
    listen 7601 ssl;
    listen [::]:7601 ssl;

    ssl_certificate     /root/cert/vkosarev.link.fullchain.pem;
    ssl_certificate_key /root/cert/vkosarev.link_privatekey.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    # Immich расположен на vkosarev.name — редиректим туда
    return 301 https://vkosarev.name:7601$request_uri;
}
