server {
    listen 80 default_server;
    server_name _;
    return 301 https://$host:1443$request_uri;
}

server {
    listen 1443 ssl default_server;
    server_name _;

    ssl_certificate     /root/cert/agghhh.click_fullchain.crt;
    ssl_certificate_key /root/cert/agghhh.click_privatekey.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

