global:
  scrape_interval: 15s      # как часто снимать метрики
  evaluation_interval: 15s  # как часто вычислять alert-правила

scrape_configs:

  - job_name: "node"
    static_configs:
      - targets:
          - "host.docker.internal:9100"
      # Для уникальности instance подменяем его на имя сервера
    relabel_configs:
      - source_labels: [__address__]
        regex: .*
        replacement: "vkosarev.name:9100"
        target_label: instance
      # Если нужно собирать с других серверов — добавить отдельные job с нужным replacement

  # 3x-ui метрики — экспортёр в той же Docker-сети, слушает на :3000
  - job_name: "xui"
    static_configs:
      - targets:
        - "host.docker.internal:3001"
        - "vkosarev.name:3001"
        - "agghhh.click:3001"
        # - "vkosarev.link:3001"  # теперь через federation

  # Federation: собираем метрики с vkosarev.link через его Prometheus
  - job_name: 'federate-vkosarev-link'
    scrape_interval: 30s
    metrics_path: '/federate'
    honor_labels: true
    params:
      'match[]':
        - '{job="node"}'
        - '{job="xui"}'
    static_configs:
      - targets:
        - 'vkosarev.link:9090'
