global:
  scrape_interval: 15s      # как часто снимать метрики
  evaluation_interval: 15s  # как часто вычислять alert-правила

scrape_configs:

  # node_exporter на этом сервере (instance подменяется на имя текущего нода)
  - job_name: "node-self"
    static_configs:
      - targets:
          - "host.docker.internal:9100"
    relabel_configs:
      - source_labels: [__address__]
        regex: .*
        # Имя текущего нода берётся из переменной окружения NODE_NAME (пример: vkosarev.name, vkosarev.link, agghhh.click)
        replacement: "$NODE_NAME:9100"
        target_label: instance

  # federation: собираем агрегированные метрики с prometheus на всех трёх нодах
  - job_name: 'federate-vkosarev.name'
    scrape_interval: 30s
    metrics_path: '/federate'
    honor_labels: true
    params:
      'match[]':
        - '{job="node"}'
        - '{job="xui"}'
    static_configs:
      - targets:
          - 'vkosarev.name:9090'

  - job_name: 'federate-vkosarev.link'
    scrape_interval: 30s
    metrics_path: '/federate'
    honor_labels: true
    params:
      'match[]':
        - '{job="node"}'
        - '{job="xui"}'
    static_configs:
      - targets:
          - 'vkosarev.link:9090'

  - job_name: 'federate-agghhh.click'
    scrape_interval: 30s
    metrics_path: '/federate'
    honor_labels: true
    params:
      'match[]':
        - '{job="node"}'
        - '{job="xui"}'
    static_configs:
      - targets:
          - 'agghhh.click:9090'
