global:
  scrape_interval: 15s      # как часто снимать метрики
  evaluation_interval: 15s  # как часто вычислять alert-правила

scrape_configs:

  # node_exporter работает на хосте, не в Docker
  # host.docker.internal резолвится в IP хоста благодаря extra_hosts в compose
  - job_name: "node"
    static_configs:
      - targets: ["host.docker.internal:9100"]
        labels:
          host: "agghhh.click"
      - targets: ["vkosarev.name:9100"]
        labels:
          host: "vkosarev.name"
