version: '3.8'

services:
  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    user: "472:472" # стандартный UID/GID grafana
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/conf:/etc/grafana
      - ./grafana/data/plugins:/var/lib/grafana/plugins
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=yourpassword # заменить на свой
    ports:
      - "3000:3000"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=90d"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"

# Для других сервисов (qBittorrent, Resilio Sync) — добавить аналогичные секции ниже
